module.exports.navigationNames = {
    Home: "Home",
    HomeTab: "HomeTab",
    CourseDetail: "CourseDetail",
    Search: "Search",
    Browse: "Browse",
    Download: "Download",
    Profile: "Profile",
    SkillDetail: "SkillDetail",
    SearchAll: "All",
    SearchCourses: "Courses",
    SearchPaths: "Paths",
    SearchAuthors: "Authors",
    Setting: "Setting",
    Register: "Register",
    SplashScreen: "SplashScreen",
    Login: "Login",
    ForgotPassword: "ForgotPassword",
    ChangePasswordForm: "ChangePasswordForm",
    MainTabs: "MainTabs",
    Authentication: "Authentication",
    AuthorProfile: "AuthorProfile",
    NewRelease: "NewRelease",
    Recommended: "Recommended",
}

module.exports.navigationTitles = {
    Home: "Home",
    Setting: "Setting",
    Browse: "Browse",
    Download: "Download",
    Profile: "Profile",
    AuthorProfile: "Author",
}