module.exports.navigationNames = {
    Home: "Home",
    MainModals: "MainModals",
    CourseDetail: "CourseDetail",
    Search: "Search",
    Browse: "Browse",
    Download: "Download",
    Profile: "Profile",
    SkillDetail: "SkillDetail",
    SearchAll: "All",
    SearchCourses: "Courses",
    SearchPaths: "Paths",
    SearchAuthors: "Authors",
    Setting: "Setting",
    Register: "Register",
    SplashScreen: "SplashScreen",
    Login: "Login",
    ForgotPassword: "ForgotPassword",
    ChangePasswordForm: "ChangePasswordForm",
    VerifyEmail: "VerifyEmail",
    MainTabs: "MainTabs",
    Authentication: "Authentication",
    AuthorProfile: "AuthorProfile",
    NewRelease: "NewRelease",
    Recommended: "Recommended",
    FullSection: "FullSection",
    ListLesson: "Contents",
    ListComments: "Comments",
}

module.exports.navigationTitles = {
    Home: "Home",
    Setting: "Setting",
    Browse: "Browse",
    Download: "Download",
    Profile: "Profile",
}

module.exports.API_LINK = `http://api.dev.letstudy.org`

module.exports.dispatchTypes = {
    LoginSuccess: `LOGIN_SUCCEED`,
    LoginFailure: `LOGIN_FAILURE`,
    LoginRequest: `LOGIN_REQUEST`,
    LogOutRequest: `LOGOUT_REQUEST`,
    RegisterRequest: `REGISTER_REQUEST`,
    RegisterSuccess: `REGISTER_SUCCESS`,
    RegisterFailure: `REGISTER_FAILURE`,
    CoursesRequest: `COURSES_REQUEST`,
    GetTopNewSuccess: `GET_TOP_NEW_SUCCESS`,
    GetTopNewFailure: `GET_TOP_NEW_FAILURE`,
    GetTopSellSuccess: `GET_TOP_SELL_SUCCESS`,
    GetTopSellFailure: `GET_TOP_SELL_FAILURE`,
    GetTopRateSuccess: `GET_TOP_RATE_SUCCESS`,
    GetTopRateFailure: `GET_TOP_RATE_FAILURE`,
    GetRecommendSuccess: `GET_RECOMMEND_SUCCESS`,
    GetRecommendFailure: `GET_RECOMMEND_FAILURE`,
    GetFavoriteSuccess: `GET_FAVORITE_SUCCESS`,
    GetFavoriteFailure: `GET_FAVORITE_FAILURE`,
    UpdateProfileRequest: `UPDATE_PROFILE_REQUEST`,
    UpdateProfileSuccess: `UPDATE_PROFILE_SUCCESS`,
    UpdateProfileFailure: `UPDATE_PROFILE_FAILURE`,
    GetCourseDetailRequest: `GET_COURSE_DETAIL_REQUEST`,
    GetCourseDetailSuccess: `GET_COURSE_DETAIL_SUCCESS`,
    GetCourseDetailFailure: `GET_COURSE_DETAIL_FAILURE`
}