export default {
    FONT_SIZE_BUTTON_TITLE: 11,
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_LARGE: 16,
    FONT_SIZE_SCREEN_TITLE: 32,
    PRIMARY_TEXT_COLOR: '#F3F4F6',
    SECONDARY_TEXT_COLOR: '#9DA0A5',
    FONT_WEIGHT_LIGHT: "200",
    FONT_WEIGHT_MEDIUM: "600",
    FONT_WEIGHT_HEAVY: "800",
    SMALL_MARGIN: 5,
    MEDIUM_MARGIN: 15,
    LARGE_MARGIN: 20
  };